# Generated by Django 5.2.12 on 2026-03-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "api_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("secret_key", models.CharField(editable=False, max_length=64)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Consumer",
                "verbose_name_plural": "Consumers",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("gerar_primos", "Gerador de Números Primos"),
                            ("pokemon", "Consulta PokéAPI"),
                            ("traduzir", "Fun Translations (Yoda, Pirata, Minion)"),
                            ("converter_pdf", "Converter PDF → Markdown (Docling)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        help_text="URL onde o resultado DESTE evento será enviado"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="webhook.consumer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
                "ordering": ["evento"],
                "unique_together": {("consumer", "evento")},
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("callback_enviado", "Callback Enviado"),
                            ("callback_falhou", "Callback Falhou"),
                        ],
                        default="recebido",
                        max_length=20,
                    ),
                ),
                ("resultado", models.JSONField(blank=True, null=True)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("assinatura_valida", models.BooleanField(default=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="webhook.consumer",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="webhook.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook",
                "verbose_name_plural": "Logs de Webhook",
                "ordering": ["-recebido_em"],
            },
        ),
    ]
